### PR TITLE
Added variable for cloudwatch Full Request and Response Logs

### PR DESCRIPTION
**Pull request by sheilman16**
## what

- Added variable `data_trace_enabled` to the `aws_api_gateway_method_settings` resource
- This change allows for configuration of CloudWatch logging setting "Full Request and Response Logs" available in the AWS UI. [2]

## why
The variable `logging_level` controls CloudWatch log setting in the AWS UI for OFF, INFO,  and ERROR, but doesn't include an option for "Full Request and Response Logs". In the AWS UI for API GW, there's an additional option, "Full Request and Response Logs", as shown in the screenshot:

image

According to terraform documentation, the variable `data_trace_enabled = true` is required in conjunction with `logging_level  = "INFO"` to enable "Full Request and Response Logs". This is added to the `aws_api_gateway_method_settings` resource in the `settings` code block [2]:

```  
settings {
    logging_level      = "INFO"
    metrics_enabled    = true
    data_trace_enabled = true
  }
```

## references
[1] Terraform resource:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_method_settings

[2] Closed Issue with Terraform citing solution
https://github.com/hashicorp/terraform-provider-aws/issues/35863#issuecomment-1954633612

### CODE REVIEW

**Comment by jamengual** [comment]
please run `make precommit/terraform` and commit the changes

**Review by jamengual — APPROVED** [review]

**Comment by sheilman16** [comment]
Do i need to make any additional changes for this ticket to move forward?

**Comment by Gowiem** [comment]
@sheilman16 this is a legit PR and should be something we get merged quickly. Apologies on not hearing a response. I'm reopening and we'll get this moved forward 👍

**Comment by Gowiem** [comment]
Kicking off another run of the tests. The failure is due to the following error: 

```
 Error: updating API Gateway Account: BadRequestException: The role ARN does not have required permissions configured. Please grant trust permission for API Gateway and add the required role policy.
TestExamplesAccountSettings 2024-03-02T02:34:41Z logger.go:66: 
TestExamplesAccountSettings 2024-03-02T02:34:41Z logger.go:66:   on ../../modules/account-settings/main.tf line 7, in resource "aws_api_gateway_account" "this":
TestExamplesAccountSettings 2024-03-02T02:34:41Z logger.go:66:    7: resource "aws_api_gateway_account" "this" {
TestExamplesAccountSettings 2024-03-02T02:34:41Z logger.go:66: 
TestExamplesAccountSettings 2024-03-02T02:34:41Z logger.go:66: 
TestExamplesAccountSettings 2024-03-02T02:34:41Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; 
Error: updating API Gateway Account: BadRequestException: The role ARN does not have required permissions configured. Please grant trust permission for API Gateway and add the required role policy.
```

Which does not look to be related to this PR. If the tests continue to fail, we'll have the Cloud Posse team look at this as it is likely an issue with test setup in their AWS account. 

@sheilman16 Unfortunately, we do need to re-generate the README again due to the above merge conflict. I'm unsure of the correct README changes in the conflict. Do you mind pull in `main` on your local branch, accepting whatever from the resulting conflict, and then just re-generating the README via the following commands? 

```
make init
make readme
```

Sorry you have to do this twice! I'll get this sorted ASAP now that I've seen it 👍

**Comment by Gowiem** [comment]
@sheilman16 now tests are passing so all good there. We just need to resolve the conflicts. Jump on that when you can and I'll quickly get you an approval once that is done!

**Comment by sheilman16** [comment]
Apologies for this, i've completed the requested updates and opened a new PR. https://github.com/cloudposse/terraform-aws-api-gateway/pull/43

**Pull request closed without merging**
