### PR TITLE
Fix error when create private API Gateway with resource policy

### PR DESCRIPTION
**Pull request by ByJacob**
## what

- add relations between `aws_api_gateway_deployment` and `aws_api_gateway_rest_api_policy`

## why

```
╷
│ Error: creating API Gateway Deployment: BadRequestException: Private REST API doesn't have a resource policy attached to it
│ 
│   with module.api_gwt.aws_api_gateway_deployment.this[0],
│   on ../../modules/api-gwt/main.tf line 39, in resource "aws_api_gateway_deployment" "this":
│   39: resource "aws_api_gateway_deployment" "this" {
│ 
╵
```

## references

- https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Review by max-lobur — DISMISSED** [review]

**Comment by jamengual** [comment]
please run `make precommit/terraform` and commit the changes.

Thanks.

**Comment by max-lobur** [comment]
Still needs `make precommit/terraform`

**Comment by max-lobur** [comment]
Checking why that readme change did not show up on a scheduled readme build. It's not coming from a PR, it's a template change from few months ago.

**Review by max-lobur — APPROVED** [review]

**Comment by max-lobur** [comment]
Should be good now, this just needed a rebase.

**Pull request merged**
